const usersdata = [
  {
    id: 1,
    name: "Chika",
    image: require("./images/chika.jpg"),
    message: "hello how are you doing today, i love to here from you",
    countmessage: 177,
  },
  {
    id: 2,
    name: "Bright",
    image: require("./images/images3.jpg"),
    message: "So sorry i was coding",
    countmessage: 177,
  },
  {
    id: 3,
    name: "Independent",
    image: require("./images/images1.jpg"),
    message: "cool i was coding with Bright C Web",
    countmessage: 177,
  },
  {
    id: 4,
    name: "Independent",
    image: require("./images/images.jpg"),
    message: "cool i was coding with Bright C Web",
    countmessage: 17,
  },
  {
    id: 5,
    name: "Independent",
    image: require("./images/images2.jpg"),
    message: "Yes Bright i know you can do it",
    countmessage: 17,
  },
  {
    id: 6,
    name: "Independent",
    image: require("./images/images1.jpg"),
    message: "Is it react native or what?",
    countmessage: 17,
  },
  {
    id: 7,
    name: "James",
    image: require("./images/images4.jpg"),
    message: "Is it react native or what?",
    countmessage: 17,
  },
  {
    id: 8,
    name: "James",
    image: require("./images/images5.jpg"),
    message: "Is it react native or what?",
    countmessage: 17,
  },
  {
    id: 9,
    name: "God is great",
    image: require("./images/images6.jpg"),
    message: "Is it react native or what?",
    countmessage: 17,
  },
  {
    id: 10,
    name: "facebook",
    image: require("./images/images7.jpg"),
    message: "How is my facebook account mr man",
    countmessage: 17,
  },
  {
    id: 11,
    name: "facebook",
    image: require("./images/images7.jpg"),
    message: "How is my facebook account mr man",
    countmessage: 17,
  },
  {
    id: 12,
    name: "Faith",
    image: require("./images/images7.jpg"),
    message: "How is my facebook account mr man",
    countmessage: 17,
  },
  {
    id: 13,
    name: "Joy",
    image: require("./images/images7.jpg"),
    message: "How is my facebook account mr man",
    countmessage: 17,
  },
  {
    id: 14,
    name: "facebook",
    image: require("./images/images7.jpg"),
    message: "How is my facebook account mr man",
    countmessage: 17,
  },
];

export default usersdata